name: Build

on:
  push:
    branches:
      - 1.21.8
      - 1.21.5
      - 1.21.4
      - 0.5.8

  pull_request:
    branches:
      - 1.21.8
      - 1.21.5
      - 1.21.4
      - 0.5.8

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Branch
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin

      - name: Make Gradle executable
        run: chmod +x gradlew

      - name: Build Mod
        run: ./gradlew build --stacktrace --no-daemon

      - name: Upload Built Jar
        uses: actions/upload-artifact@v4
        with:
          name: mod-${{ github.ref_name }}
          path: build/libs/*.jar
